### ISSUE TITLE
Possibly Related Work

### ISSUE THREAD

**Issue by YanjieZe** [apexrl/Diff4RLSurvey#2]
Diffusion Reward: Learning Rewards via Conditional Video Diffusion: https://diffusion-reward.github.io/

**Comment by zbzhu99** [comment]
Thank you for referring to this paper. I read the article and found the idea interesting. Also, the paper is highly related to the topic of our survey. The paper has been included in this repo and will be added to our survey paper in the next update.

**Comment by YanjieZe** [comment]
Thank you!
